version: '3.8'

services:
  sui-price-oracle:
    # the hash is dependent on the architecture for which docker image is built
    # for arm64 use: sha256:4842f2290e7c5d42c75d80de5a5a5042b37ad7eda541d92da2d2a588585e46ed
    # for amd64 use: sha256:
    image: prored/sui-price-oracle@sha256:4842f2290e7c5d42c75d80de5a5a5042b37ad7eda541d92da2d2a588585e46ed
    container_name: sui-price-oracle
    restart: unless-stopped
    init: true
    network_mode: host
    volumes:
      - /app/ecdsa.sec:/app/ecdsa.sec:ro