version: '3.8'

services:
  sui-price-oracle:
    image: prored/sui-price-oracle:rust-latest
    container_name: sui-price-oracle
    restart: unless-stopped
    network_mode: host
    volumes:
      - /app/ecdsa.sec:/app/ecdsa.sec:ro