version: '3.8'

services:
  sui-price-oracle:
    # the hash is dependent on the architecture for which docker image is built
    # for arm64 use: sha256:f0f20def149b3f418b1b43de9c0d9309c93199f459e63fbe9831ac0e7719d0be
    # for amd64 use: sha256:
    image: prored/sui-price-oracle@sha256:f0f20def149b3f418b1b43de9c0d9309c93199f459e63fbe9831ac0e7719d0be
    container_name: sui-price-oracle
    restart: unless-stopped
    init: true
    network_mode: host
    volumes:
      - /app/ecdsa.sec:/app/ecdsa.sec:ro