[testnet]
package_id = "0x20b65f52a0bab5d43e408a67af7c0d4abbe7f721973a5e6e76cb18c54450f705" # modules - enclave, oyster_demo
Cap = "0x7e8199ca0e8298f01765ab52492b70cef5ffe6348b5f16f5e1bdaaedc6cd9a25"
EnclaveConfig = "0x66acfd06236812214d93b073f43a89c3da2a90b14b512f7fa9dea33526c7288f"
UpgradeCap = "0xa4be56a45004d3e21770942b1c28c086778a4d87d538a7ae43e7be045f70a2b4"
rpc_url = "https://fullnode.testnet.sui.io:443"