[testnet]
package_id = "0x0" # modules - enclave, oyster_demo
EnclaveRegistry = "0x0" # shared object from enclave::init
PriceOracle = "0x0" # shared object from oyster_demo::init
AdminCap = "0x0" # owned by deployer, for updating expected PCRs
UpgradeCap = "0x0"
rpc_url = "https://fullnode.testnet.sui.io:443"
