[testnet]
package_id = "0x889f8cd16439ce0af513962d0ba94e41ffb8d91ccf6f4369920dddb68f50fa23" # modules - enclave, oyster_demo
Cap = "0x7e849d0bbee65ff912ed90eebb548d24cd96e7f39c3c933d37e84baad3f3e0eb"
EnclaveConfig = "0x56b3b1cc12565dd402d7ff2028492e1cd8e83aafaa9931d0eb8480c706e5e470"
UpgradeCap = "0x7869075d57655f13f8ba638d1c99017fce155b6465235b4b70e7965b76068f23"
PriceOracle = "0x28a88b740bd36a3ee57eaece0593eb7dc844d6232cacd65a229ce4a75ddbee5f"
rpc_url = "https://fullnode.testnet.sui.io:443"