[testnet]
enclave_registry_package_id = "0x8c85df70f6bf50107bbb6e5f669ad9d8077de18bae160b6b45f328d4970dc9fb" # enclave_registry package
oyster_demo_package_id = "0x0" # oyster_demo package
Registry = "0x2e383f908c48c70bd1d6945e49a708a0a6bf1a74805e88950969578340d85e6c" # shared object from enclave_registry::init
PriceOracle = "0x0" # shared object from oyster_demo::init
AdminCap = "0x0" # owned by deployer, for updating expected PCRs
UpgradeCap_registry = "0x217b7a5e647c880614c0147057a5f42570e2837484c1fd3dbc1fbcbec5536c2a"
rpc_url = "https://fullnode.testnet.sui.io:443"
