[mainnet]
enclave_registry_package_id = "0x8df76b79118ffad2bacb55705c84474802ddb3d62199b98db720c5088e161ab8" # pre-deployed, referenced via published-at in EnclaveRegistry/Move.toml
Registry = "0xf67a9392da1749e8442d71eb6139a9dc1c199b88ef3da49385eeda175246d9d0" # pre-deployed shared object from enclave_registry::init
UpgradeCap_registry = "0xc96e5666fc5cf094045c1900a9e9bf75946e304b9593f61e74d0833ab126118e"
rpc_url = "https://fullnode.mainnet.sui.io:443"

[testnet]
enclave_registry_package_id = "0x05cd5a306375c49727fc2f1e667df8bcc1f5b52ad07e850074d330afda932761" # pre-deployed, referenced via published-at in EnclaveRegistry/Move.toml
Registry = "0x7ebc3f9bc7a0cf0820d241ad767036483b885bbd62636fb9446bb0d99d2ed091" # pre-deployed shared object from enclave_registry::init
UpgradeCap_registry = "0x1b867205d83b5b04685c7d60f43461c2338057d683f10b6fe8a4fc5f3b6160d0"
rpc_url = "https://fullnode.testnet.sui.io:443"